import type { ReceiptData } from "./Props/Data";

export const testData: ReceiptData[] = [
  {id:1,
    name: "เดชาธร",
    address: "",
    tel: "",
    dateRealFormat:"",
    date: "",
    room: "",
    month: "",
    waterMeterCurr: "0",
    waterMeterPrev: "0",
    waterMeterUsed: "0",
    electricMeterCurr: "0",
    electricMeterPrev: "0",
    electricMeterUsed: "0",
    items: {
      rent: { checked: true, amount: "5000" },
      water: { checked: false, amount: "0" },
      electric: { checked: false, amount: "0" },
      internet: { checked: false, amount: "0" },
      fee: { checked: false, amount: "0" },
      other: { checked: false, amount: "0" },
    },
    Receiver: "",
    bankName: "",
    accountName: "",
    accountNumber: "",
  },
  {id:2,
    name: "อำนาจ",
    address: "",
    tel: "",
    dateRealFormat:"",
    date: "",
    room: "",
    month: "",
    waterMeterCurr: "0",
    waterMeterPrev: "0",
    waterMeterUsed: "0",
    electricMeterCurr: "0",
    electricMeterPrev: "0",
    electricMeterUsed: "0",
    items: {
      rent: { checked: true, amount: "5000" },
      water: { checked: false, amount: "0" },
      electric: { checked: false, amount: "0" },
      internet: { checked: false, amount: "0" },
      fee: { checked: false, amount: "0" },
      other: { checked: false, amount: "0" },
    },
    Receiver: "",
    bankName: "",
    accountName: "",
    accountNumber: "",
  },
  {id:3,
    name: "นก",
    address: "",
    tel: "",
    dateRealFormat:"",
    date: "",
    room: "",
    month: "",
    waterMeterCurr: "0",
    waterMeterPrev: "0",
    waterMeterUsed: "0",
    electricMeterCurr: "0",
    electricMeterPrev: "0",
    electricMeterUsed: "0",
    items: {
      rent: { checked: true, amount: "5000" },
      water: { checked: false, amount: "0" },
      electric: { checked: false, amount: "0" },
      internet: { checked: false, amount: "0" },
      fee: { checked: false, amount: "0" },
      other: { checked: false, amount: "0" },
    },
    Receiver: "",
    bankName: "",
    accountName: "",
    accountNumber: "",
  },
];